### ISSUE TITLE
Postawienie Strapi na Elektron Cloud

### ISSUE THREAD

**Issue by konhi** [ElektronPlus/school-website#1]
dobrze, gdyby:
- api było publiczne
- były kopie zapasowe bazy danych

**Comment by Wybranowsky** [comment]
kto nie zapisuje ten długo pracuje! HAHAHAHA~ Waldemar Drapikowski

**Comment by Wybranowsky** [comment]
Api jest publiczne np. https://strapi.elektronplus.pl/api/articles
